[package]
name = "lk_math"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Tools for solving commonly occuring mathematical problems"
repository = "https://github.com/lubomirkurcak/lk_math/"
keywords = ["math", "algebra", "geometry", "calculus", "algorithm"]
categories = ["algorithms", "data-structures", "game-development", "mathematics", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

